### ISSUE TITLE
Motion device node displays the "contact" gateway device only

### ISSUE THREAD

**Issue by vladmrk** [pierrecle/node-red-contrib-mi-devices#6] opened 2018-01-04 20:05 UTC
In v1.0.3 when I am trying to configure the Motion device, it only accepts the "contact" device which is set in the Gateway configurator.

In the configurator I have added all devices to point to the same SID in order to test this.

Here's a screenshot.  

![image](https://user-images.githubusercontent.com/1914561/34581970-a9ed3b06-f192-11e7-87b9-d361c2e9f722.png)

**Comment by bemble** [comment] 2018-01-04 20:52
Strange, I cannot reproduce this. I added a motion device in the gateway, added a motion node and it filter well the motion device.
Did you restart nodered after update? Did yo uninstall node-red-contrib-xiaomi-devices (I did not change node types so it should have conflicts when using both modules at the same time)?

**Comment by vladmrk** [comment] 2018-01-04 21:06
Yep, I have tried restarts and have uninstalled the node-red-contrib-xiaomi-devices.

I also noticed two other issues with the Motion node:

- I could only get to see the battery status once in the past couple of days (52%). Other times it is the default N/A.
- whenever I deploy, I get this warning in the log: [warn] [xiaomi-gateway in:Xiaomi Gateway] udp.errors.alreadyused

Here the config in the Gateway configurator node, each device type corresponds to the text:

![image](https://user-images.githubusercontent.com/1914561/34584150-e620f290-f19a-11e7-9ca8-9efe6e4246c0.png)

**Comment by bemble** [comment] 2018-01-04 21:36
Could send me the code of your flow (select the nodes, menu > export > Clipboard > Selected nodes)?
Do you have multiple gateways? My problem is I didn't own a motion sensor yet and when I look at the code it should be ok...

**Comment by vladmrk** [comment] 2018-01-04 21:59
Here it is, don't forget to change the IP and Key of the gateway.

> [{"id":"624f0a4c.6345f4","type":"xiaomi-motion","z":"714a8937.b60e28","gateway":"7fa62fa0.40231","name":"contact","sid":"158d0001d68a24","motionmsg":"","nomotionmsg":"","output":"0","x":169.5,"y":656,"wires":[["d8e57f7.fdcc48","eda5b353.149bf"]]},{"id":"7b280bcf.3321a4","type":"xiaomi-gateway in","z":"714a8937.b60e28","name":"Xiaomi Gateway","gateway":"7fa62fa0.40231","ip":"192.168.0.100","x":85,"y":725,"wires":[["624f0a4c.6345f4","918f1377.34969"]]},{"id":"7fa62fa0.40231","type":"xiaomi-configurator","z":"","name":"Xiaomi Gateway","ip":"192.168.0.100","sid":"34ce008aedd6","deviceList":[{"sid":"158d0001d68a24","desc":"ht","model":"sensor_ht"},{"sid":"158d0001d68a24","desc":"contact","model":"magnet"},{"sid":"158d0001d68a24","desc":"motion","model":"motion"},{"sid":"158d0001d68a24","desc":"plug","model":"plug"},{"sid":"158d0001d68a24","desc":"switch","model":"switch"}],"key":"GATEWAYKEY"}]

**Comment by vladmrk** [comment] 2018-01-04 22:01
Oh, and I have only one gateway.

**Comment by bemble** [comment] 2018-01-05 09:06
I imported your configuration and.. no problem on my side, as you can see (your named node "contact" is a motion node and successfully list only motion nodes). What is your nodered version?
<img width="352" alt="capture d ecran 2018-01-05 a 10 01 56" src="https://user-images.githubusercontent.com/397503/34602451-10f8baba-f200-11e7-8ea3-35c67e90b2ac.png">
<img width="495" alt="capture d ecran 2018-01-05 a 10 02 04" src="https://user-images.githubusercontent.com/397503/34602452-110c8e50-f200-11e7-9b3d-8a23aef29391.png">

**Comment by vladmrk** [comment] 2018-01-05 09:12
Node-RED version: v0.17.5
Node.js  version: v6.12.2
Running on Pi 3 Model B

Regardless of this dropdown issue, the motion sensor works and I get the events from it. So I think we can close this for now, I am guessing there is some fault in the gateway maybe (even though in the MI iOS app I have configured the device as a Motion sensor)..

**Comment by vladmrk** [comment] 2018-01-05 09:12
Thanks for all the help!

**Comment by bemble** [comment] 2018-01-05 09:25
Ok, on my side I'm running on:
Node-RED version: v0.17.5
Node.js version: v9.3.0
Running on Pi 3 Model B

In fact, motion, magnet and switch nodes have the exact same behaviors. Contrary to the original module, I only filter incoming messages on device SID, not its model anymore. So, you can use the model you want, it's only a visual helper. Things are different for sensors ht, because data are processed.

I agree, I close this issue for now, if anybody else have this issue, feel free to reopen.
Thanks anyway for the feedback.

**Closed as completed by bemble** 2018-01-05 09:25 UTC
